### ISSUE TITLE
Use API instead of scrapping

### ISSUE THREAD

**Issue by jonatanklosko** [uesyuu/WCALive_bot#1]
Hey, I see you run headless browser to render the UI and scrap content. An alternative approach would be to just query the internal API. It uses Graphql, here's an example request getting the records data:

```bash
 curl -X POST -H "Content-Type: application/json" --data '{ "query": "{ recentRecords { competition { id name } event { name } round { id } type recordTag attemptResult result { person { name country { name } } } } }" }' https://live.worldcubeassociation.org/api
```

You can see what's available [here](https://github.com/thewca/wca-live/blob/dfff5f42030e128c8fbceb87abf0f81dee558b9e/server/schema.graphql#L49-L57). Internal API is obviously a subject to change, but so is the UI ^^

It's just a suggestion, but I'm pretty sure it would be more convenient and efficient to just use the API.

**Comment by uesyuu** [comment]
@jonatanklosko 
Sorry for my late reply.
Thank you for your advice! I changed the code to use GraqhQL API of WCA Live.

I'd like to ask, is there an API that converts an int value of time into a formal record string? For MBLD, converting the int value into a record string is a daunting task.

**Comment by jonatanklosko** [comment]
There's no such API that I know of. It definitely is a bit of encoding, but that's the kind of logic you write once and use whenever needed ^^

*Sidenote: the WCA Live API will probably change as I currently work on a rework, but the query itself should stay very similar. I will take a note to let you know once the changes are in place (hopefully in ~1 month or so).*

**Comment by jonatanklosko** [comment]
Hey, so JFYI I deployed the reworked app today, hopefully nothing unexpected comes up ^^ With the new API a query for the same data looks like so:

```graphql
{
  recentRecords {
    type
    tag
    attemptResult
    result {
      person {
        name
        country {
          name
        }
      }
      round {
        id
        competitionEvent {
          event {
            id
            name
          }
          competition {
            id
            name
          }
        }
      }
    }
  }
}
```

`curl` example:

```shell
curl -X POST -H "Content-Type: application/json" --data '{ "query": "{ recentRecords { type tag attemptResult result { person { name country { name } } round { id competitionEvent { event { id name } competition { id name } } } } } }" }' https://live.worldcubeassociation.org/api
```

If there are any issues, let me know =)

**Comment by uesyuu** [comment]
Thanks for telling me!
The query has been fixed.

**Comment by jonatanklosko** [comment]
Great :shipit:
